Disable Duplicate Method Calls
ProctorU/guides pull request #36
Opened 2018-02-20 15:45 UTC by king601

CodeClimate will throw a bunch of errors when you call a method multiple times without assigning it to a variable. 

Often times, we don't assign something to a variable because it'd add an additional line for no real benefit.

2018-02-20 15:47 UTC, licatajustin requested changes
Can you instead add to our [Reek configuration](https://github.com/ProctorU/guides/blob/master/style/ruby/config.reek)?

2018-02-20 15:59 UTC, king601 commented
Thanks @licatajustin I didn't see this before. Great catch!

2018-02-20 21:33 UTC, licatajustin approved these changes

2018-02-21 18:48 UTC, tmiller approved these changes

2018-02-21 19:32 UTC, dwilkins approved these changes
I regret that I have only one vote to cast

2018-02-21 19:33 UTC, merged