Add custom cop to detect potentially unsafe usage of default database columns
ProctorU/guides pull request #56
Opened 2019-08-20 14:00 UTC by jamescook

@Tetramputechture Will this work with our CC config? I don't know how it pulls in the rubocop config so I worry it doesn't support custom extensions.

Attached is the output of running this custom cop over db/migration in Archimedes.
[unsafe_migrations.txt](https://github.com/ProctorU/guides/files/3520978/unsafe_migrations.txt)

2019-08-20 14:23 UTC, Tetramputechture requested changes

2019-08-20 14:23 UTC, Tetramputechture commented on style/ruby/extensions/unsafe_migration.rb
> +          if node && node.respond_to?(:children) && node.children.any?
```suggestion
          if node.try(:children)
```

2019-08-23 19:45 UTC, jamescook commented
@Tetramputechture The version of Rubocop bundled with CC (0.52.1) doesn't support some of the pattern expressions I've written:

```
14:34 $ docker run   --interactive --tty --rm   --env CODECLIMATE_CODE="$PWD"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc   codeclimate/codeclimate analyze -e rubocop db/migrate/20140812032549_add_take_it_now_to_iterations.rb
Starting analysis
Running rubocop: Done!
error: (CC::CLI::Analyze::EngineFailure) engine rubocop failed with status 1 and stderr
NOTE: Gem.gunzip is deprecated; use Gem::Util.gunzip instead. It will be removed on or after 2018-12-01.
Gem.gunzip called from /usr/local/bundle/gems/unicode-display_width-1.3.0/lib/unicode/display_width/index.rb:5.
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/node_pattern.rb:458:in `fail_due_to': Couldn't compile due to invalid token "<". Pattern: (hash <$(pair (sym :default) !nil) ...>) (RuboCop::NodePattern::Invalid)
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/node_pattern.rb:168:in `compile_expr'
```
But it worked on Rubocop 0.73

An alternative option is for CircleCI to have a separate build step that runs this custom cop under a newer Rubocop version. We can fail the build if it finds a violation.

cc @tmiller

2019-11-19 16:37 UTC, kirylrb approved these changes

2019-12-11 15:28 UTC, jamescook commented
@nick I found this can be resolved by the following changes in .codeclimate.yml in our other repos (bumping the rubocop channel):

```diff
diff --git a/.codeclimate.yml b/.codeclimate.yml
index 61cda0c7c9..cc69da67eb 100644
--- a/.codeclimate.yml
+++ b/.codeclimate.yml
@@ -43,9 +43,11 @@ checks:

 prepare:
   fetch:
-    - "https://raw.githubusercontent.com/ProctorU/guides/master/style/ruby/.rubocop.yml"
+    - "https://raw.githubusercontent.com/ProctorU/guides/james/add-cop-for-default-column-values/style/ruby/.rubocop.yml"
     - "https://raw.githubusercontent.com/ProctorU/guides/master/style/ruby/config.reek"
     - "https://raw.githubusercontent.com/ProctorU/guides/master/style/scss/.scss-lint.yml"
+    - url: "https://raw.githubusercontent.com/ProctorU/guides/james/add-cop-for-default-column-values/style/ruby/extensions/unsafe_migration.rb"
+      path: "extensions/unsafe_migration.rb"

 plugins:
   brakeman:
@@ -56,7 +58,7 @@ plugins:
     enabled: true
   rubocop:
     enabled: true
-    channel: rubocop-0-54
+    channel: rubocop-0-72
```

2020-09-30 14:14 UTC, ghouston approved these changes
looks good, does what it says.  (produces 34 offences when run on the 2020 migrations.)

```
bundle exec rubocop --only Migration/UnsafeMigration -c ../guides/style/ruby/.rubocop.yml db/migrate/2020*
...
90 files inspected, 34 offenses detected
```

30% of migrations produced this warning.  that is noisy, but i guess its necessary.

2020-10-01 10:39 UTC, jamescook commented
I'm going to extract the custom cop into a gem to make it easier to integrate with external projects.

2021-05-03 13:28 UTC, closed without merging